# Generated by SmooAI/smooth release v0.29.0. Do not edit by hand —
# the next release will overwrite. See SmooAI/smooth release.yml
# (pearl th-e32f60) for the source of truth.
class Th < Formula
  desc "Smoo AI CLI — agent orchestration, config management, and platform tools"
  homepage "https://github.com/SmooAI/smooth"
  version "0.29.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/SmooAI/smooth/releases/download/v0.29.0/th-macos-arm64.tar.gz"
      sha256 "082cf99f95a3e7b4cd55dcbfe1cdee19540319cd1940b851f0497873ba9c36e0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SmooAI/smooth/releases/download/v0.29.0/th-linux-arm64.tar.gz"
      sha256 "d1702c88fc12bd4b90495a1092ad632ae2c956e99c5e683251d184bb2b811754"
    end
    on_intel do
      url "https://github.com/SmooAI/smooth/releases/download/v0.29.0/th-linux-x86_64.tar.gz"
      sha256 "44c38969663b1c8a7c3f021430d264f1ad307957b8295403d31c5975c97b4eec"
    end
  end

  def install
    bin.install "th"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/th --version")
  end
end
