# Generated by SmooAI/smooth release v0.64.0. Do not edit by hand —
# the next release will overwrite. See SmooAI/smooth release.yml
# (pearl th-e32f60) for the source of truth.
class Th < Formula
  desc "Smoo AI CLI — agent orchestration, config management, and platform tools"
  homepage "https://github.com/SmooAI/smooth"
  version "0.64.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/SmooAI/smooth/releases/download/v0.64.0/th-macos-arm64.tar.gz"
      sha256 "789b881b8144d4ea7cb2b5925247fe76bbde9776d27bd28b34a6e36eef377713"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SmooAI/smooth/releases/download/v0.64.0/th-linux-arm64.tar.gz"
      sha256 "e5da4e4231e8ada97f05e1214398efaf7df0ed18e60d7f02b3995b1a683c32db"
    end
    on_intel do
      url "https://github.com/SmooAI/smooth/releases/download/v0.64.0/th-linux-x86_64.tar.gz"
      sha256 "a0752d1a8197a60c496d9079f45f369c98222208243defc20f445be491db4e1a"
    end
  end

  def install
    bin.install "th"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/th --version")
  end
end
