# Generated by SmooAI/smooth release v0.15.0. Do not edit by hand —
# the next release will overwrite. See SmooAI/smooth release.yml
# (pearl th-e32f60) for the source of truth.
class Th < Formula
  desc "Smoo AI CLI — agent orchestration, config management, and platform tools"
  homepage "https://github.com/SmooAI/smooth"
  version "0.15.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/SmooAI/smooth/releases/download/v0.15.0/th-macos-arm64.tar.gz"
      sha256 "4620ae678480467cd492e2d7bca90ec3b968a1e4f0ec206204f83895a71e130c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SmooAI/smooth/releases/download/v0.15.0/th-linux-arm64.tar.gz"
      sha256 "8606a0e09c3197a2f26a8698e9822afbb5bee8a76fa02123cecb5f3f0f84fb70"
    end
    on_intel do
      url "https://github.com/SmooAI/smooth/releases/download/v0.15.0/th-linux-x86_64.tar.gz"
      sha256 "c6a137441010f52b4136f995cfc99f011ef3678acb1e699c61209ee3e9fa4a65"
    end
  end

  def install
    bin.install "th"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/th --version")
  end
end
